//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class FrmMenuPrincipal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        private System.Windows.Forms.Panel pContenido;
        private System.Windows.Forms.Button btnVolverLogin;
        private System.Windows.Forms.Button btnSalir;
        private System.Windows.Forms.Button btnClientes;
        private System.Windows.Forms.Button btnVentas;
        private System.Windows.Forms.Button btnStock;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heladeria.FrmMenuPrincipal", typeof(FrmMenuPrincipal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmMenuPrincipal));
            this.pContenido = new System.Windows.Forms.Panel();
            this.btnVolverLogin = new System.Windows.Forms.Button();
            this.btnSalir = new System.Windows.Forms.Button();
            this.btnClientes = new System.Windows.Forms.Button();
            this.btnVentas = new System.Windows.Forms.Button();
            this.btnStock = new System.Windows.Forms.Button();
            this.lblCantidadDeVentasTitulo = new System.Windows.Forms.Label();
            this.lblCantidadDeVentas = new System.Windows.Forms.Label();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.toolTip2 = new System.Windows.Forms.ToolTip(this.components);
            this.toolTip3 = new System.Windows.Forms.ToolTip(this.components);
            this.toolTip4 = new System.Windows.Forms.ToolTip(this.components);
            this.SuspendLayout();
            // 
            // pContenido
            // 
            this.pContenido.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pContenido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pContenido.BackgroundImage")));
            this.pContenido.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pContenido.Location = new System.Drawing.Point(12, 52);
            this.pContenido.Name = "pContenido";
            this.pContenido.Size = new System.Drawing.Size(786, 419);
            this.pContenido.TabIndex = 0;
            // 
            // btnVolverLogin
            // 
            this.btnVolverLogin.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(114)))), ((int)(((byte)(178)))));
            this.btnVolverLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVolverLogin.BackgroundImage")));
            this.btnVolverLogin.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnVolverLogin.Location = new System.Drawing.Point(12, 23);
            this.btnVolverLogin.Name = "btnVolverLogin";
            this.btnVolverLogin.Size = new System.Drawing.Size(24, 24);
            this.btnVolverLogin.TabIndex = 1;
            this.btnVolverLogin.UseVisualStyleBackColor = false;
            this.btnVolverLogin.Click += new System.EventHandler(this.btnVolverLogin_Click);
            // 
            // btnSalir
            // 
            this.btnSalir.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSalir.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(114)))), ((int)(((byte)(178)))));
            this.btnSalir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSalir.BackgroundImage")));
            this.btnSalir.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSalir.Location = new System.Drawing.Point(779, 25);
            this.btnSalir.Name = "btnSalir";
            this.btnSalir.Size = new System.Drawing.Size(19, 19);
            this.btnSalir.TabIndex = 2;
            this.btnSalir.UseVisualStyleBackColor = false;
            this.btnSalir.Click += new System.EventHandler(this.btnSalir_Click);
            // 
            // btnClientes
            // 
            this.btnClientes.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnClientes.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(114)))), ((int)(((byte)(178)))));
            this.btnClientes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClientes.BackgroundImage")));
            this.btnClientes.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnClientes.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.btnClientes.Location = new System.Drawing.Point(217, 484);
            this.btnClientes.Name = "btnClientes";
            this.btnClientes.Size = new System.Drawing.Size(30, 30);
            this.btnClientes.TabIndex = 3;
            this.btnClientes.UseVisualStyleBackColor = false;
            this.btnClientes.Click += new System.EventHandler(this.btnClientes_Click);
            // 
            // btnVentas
            // 
            this.btnVentas.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.btnVentas.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(114)))), ((int)(((byte)(178)))));
            this.btnVentas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVentas.BackgroundImage")));
            this.btnVentas.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnVentas.Location = new System.Drawing.Point(389, 484);
            this.btnVentas.Name = "btnVentas";
            this.btnVentas.Size = new System.Drawing.Size(30, 30);
            this.btnVentas.TabIndex = 4;
            this.btnVentas.UseVisualStyleBackColor = false;
            this.btnVentas.Click += new System.EventHandler(this.btnVentas_Click);
            // 
            // btnStock
            // 
            this.btnStock.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnStock.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(114)))), ((int)(((byte)(178)))));
            this.btnStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStock.BackgroundImage")));
            this.btnStock.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnStock.Location = new System.Drawing.Point(554, 484);
            this.btnStock.Name = "btnStock";
            this.btnStock.Size = new System.Drawing.Size(35, 35);
            this.btnStock.TabIndex = 5;
            this.btnStock.UseVisualStyleBackColor = false;
            this.btnStock.Click += new System.EventHandler(this.btnStock_Click);
            // 
            // lblCantidadDeVentasTitulo
            // 
            this.lblCantidadDeVentasTitulo.AutoSize = true;
            this.lblCantidadDeVentasTitulo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblCantidadDeVentasTitulo.ForeColor = System.Drawing.Color.White;
            this.lblCantidadDeVentasTitulo.Location = new System.Drawing.Point(53, 25);
            this.lblCantidadDeVentasTitulo.Name = "lblCantidadDeVentasTitulo";
            this.lblCantidadDeVentasTitulo.Size = new System.Drawing.Size(145, 21);
            this.lblCantidadDeVentasTitulo.TabIndex = 6;
            this.lblCantidadDeVentasTitulo.Text = "Cantidad de ventas:";
            // 
            // lblCantidadDeVentas
            // 
            this.lblCantidadDeVentas.AutoSize = true;
            this.lblCantidadDeVentas.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblCantidadDeVentas.ForeColor = System.Drawing.Color.White;
            this.lblCantidadDeVentas.Location = new System.Drawing.Point(198, 25);
            this.lblCantidadDeVentas.Name = "lblCantidadDeVentas";
            this.lblCantidadDeVentas.Size = new System.Drawing.Size(0, 21);
            this.lblCantidadDeVentas.TabIndex = 7;
            // 
            // FrmMenuPrincipal
            // 
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(114)))), ((int)(((byte)(178)))));
            this.ClientSize = new System.Drawing.Size(810, 525);
            this.Controls.Add(this.lblCantidadDeVentas);
            this.Controls.Add(this.lblCantidadDeVentasTitulo);
            this.Controls.Add(this.btnClientes);
            this.Controls.Add(this.btnStock);
            this.Controls.Add(this.btnVentas);
            this.Controls.Add(this.btnSalir);
            this.Controls.Add(this.btnVolverLogin);
            this.Controls.Add(this.pContenido);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FrmMenuPrincipal";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FrmMenuPrincipal_FormClosing);
            this.Load += new System.EventHandler(this.FrmMenuPrincipal_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        private System.Windows.Forms.Label lblCantidadDeVentasTitulo;
        private System.Windows.Forms.Label lblCantidadDeVentas;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.ToolTip toolTip2;
        private System.Windows.Forms.ToolTip toolTip3;
        private System.Windows.Forms.ToolTip toolTip4;
    }
}
